### ISSUE TITLE
Catálogo - Consultar Productos Disponibles

### ISSUE THREAD

**Issue by paulocoronado** [paulocoronado/AteneaMarket#1]

**Comment by camilavel** [comment]
Se creo la plantilla de la historia de usuario. Se requiere reunirnos con la Product Owner

**Comment by camilavel** [comment]
Se realizo la Reunión con el Product Owner y se creo la historia de usuario.

https://docs.google.com/document/d/15ImNgSSiJwK_uQrfgLRZ1gcOIIa-5kWvcu9NHf9CnwQ/edit?usp=sharing

**Comment by EblissYisse** [comment]
El día 1 del mes de junio de 2023, en reunión con uno de los miembros del equipo Scrum, discutimos los requerimientos para "consultar productos disponibles" y se creó la historia de usuario aprobada por ambas partes.

**Comment by camilavel** [comment]
El día de hoy se colono el repositorio y se creo la rama CatalogoDev

**Comment by paulocoronado** [comment]
Se crea la rama coronado_dev y se empieza el desarrollo de esta historia en dicha rama.

**Comment by paulocoronado** [comment]
Se desarrolla la historia agregando el controlador y las rutas correspondientes

**Comment by paulocoronado** [comment]
Se cierra el requerimiento porque se fusiona con la historia de usuario de Consultar producto por categoría
